apiVersion: v2
name: argo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: argo
    version: 0.16.8
    repository: https://argoproj.github.io/argo-helm
