argo:
  useDefaultArtifactRepo: true
  controller:
    containerRuntimeExecutor: pns
  artifactRepository:
    archiveLogs: true
    s3:
      accessKeySecret:
        name: minio-secret
        key: accesskey
      secretKeySecret:
        name: minio-secret
        key: secretkey
      insecure: true
      bucket: argo-artifacts
      endpoint: minio.default:9000