apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-workflow-reader-role-binding
subjects:
  - kind: ServiceAccount
    name: ai-workflow-reader
    namespace: {{.Release.Namespace}}
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: ai-workflow-reader-role
  apiGroup: rbac.authorization.k8s.io