apiVersion: v2
name: workflow-manager-db
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
  - name: mongodb
    version: 10.12.2
    repository: https://charts.bitnami.com/bitnami
